"""add client_event_id

Revision ID: 4e9fbaff081e
Revises: 83a312bdf776
Create Date: 2026-01-08 16:50:58.721723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9fbaff081e'
down_revision = '83a312bdf776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_event_id', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint('uq_vin_client_event', ['vin', 'client_event_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_record', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vin_client_event', type_='unique')
        batch_op.drop_column('client_event_id')

    # ### end Alembic commands ###
