"""init

Revision ID: 83a312bdf776
Revises: 
Create Date: 2025-12-26 13:50:36.839236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a312bdf776'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=32), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('standard_json', sa.Text(), nullable=True),
    sa.Column('detected_json', sa.Text(), nullable=True),
    sa.Column('compare_json', sa.Text(), nullable=True),
    sa.Column('overall', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_record_vin'), ['vin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_record_vin'))

    op.drop_table('inspection_record')
    # ### end Alembic commands ###
