"""add inspection_session and inspection_frame tables

Revision ID: a1e8244ddc81
Revises: 4e9fbaff081e
Create Date: 2026-06-22 13:48:13.680269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a1e8244ddc81'
down_revision = '4e9fbaff081e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = inspect(bind)
    existing_tables = set(insp.get_table_names())

    # color_prototype 在历史上由 db.create_all() 直接创建，这里做幂等处理
    if 'color_prototype' not in existing_tables:
        op.create_table('color_prototype',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('feature', sa.String(length=64), nullable=False),
        sa.Column('label', sa.String(length=64), nullable=False),
        sa.Column('lab_l', sa.Float(), nullable=False),
        sa.Column('lab_a', sa.Float(), nullable=False),
        sa.Column('lab_b', sa.Float(), nullable=False),
        sa.Column('n', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('feature', 'label', name='uq_feature_label')
        )
    op.create_table('inspection_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=32), nullable=False),
    sa.Column('client_session_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('standard_json', sa.Text(), nullable=True),
    sa.Column('aggregated_json', sa.Text(), nullable=True),
    sa.Column('compare_json', sa.Text(), nullable=True),
    sa.Column('overall', sa.String(length=8), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin', 'client_session_id', name='uq_session_vin_client')
    )
    with op.batch_alter_table('inspection_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_session_vin'), ['vin'], unique=False)

    op.create_table('inspection_frame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('detected_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['inspection_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'frame_index', name='uq_frame_session_index')
    )
    with op.batch_alter_table('inspection_frame', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_frame_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_frame', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_frame_session_id'))

    op.drop_table('inspection_frame')
    with op.batch_alter_table('inspection_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_session_vin'))

    op.drop_table('inspection_session')
    # 注意：不在 downgrade 里删除 color_prototype，
    # 因为它本身是上线后才被纳入迁移管理的，删除会丢失校准数据
    # ### end Alembic commands ###
